import {StyleSheet, Platform} from 'react-native';
import {Dimensions} from 'react-native';
import normalize from '../../constants/normlize';
const width = Dimensions.get('window').width;
const height = Dimensions.get('window').height;
const styles = StyleSheet.create({
  container: {
    height: height,
    width: width,
  },
  topPart: {
    height: height * 0.25,
    width: width,
    backgroundColor: '#0C365A',
    paddingLeft: width * 0.05,
    paddingRight: width * 0.05,
  },
  bottomPart: {
    height: height * 0.7,
    width: width,
    backgroundColor: '#fff',
    paddingLeft: width * 0.05,
    paddingRight: width * 0.05,
    borderTopLeftRadius: width * 0.05,
    borderTopRightRadius: width * 0.05,
    position: 'absolute',
    bottom: 70,
  },
  headerTop: {
    height: height * 0.06,
    marginTop: height * 0.02,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  iconHeader: {
    height: height * 0.035,
    width: height * 0.035,
    resizeMode: 'contain',
  },
  HeaderText: {
    fontSize: normalize(25),
    color: 'white',
    alignSelf: 'flex-start',
    fontFamily: 'AvenirNextLTPro-Bold',
    // marginLeft: width * 0.01,
  },
  limitTab: {
    width: '100%',
    height: height * 0.05,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginTop: height * 0.03,
  },
  limitIcon: {
    height: width * 0.04,
    width: width * 0.04,
    resizeMode: 'contain',
  },
  limitText: {
    fontSize: normalize(17),
    color: '#222222',
    fontFamily: 'AvenirNextLTPro-Demi',
    marginLeft: width * 0.02,
  },
  nameText: {
    fontSize: normalize(25),
    color: 'white',
    alignSelf: 'flex-start',
    letterSpacing: width * 0.005,
    fontFamily: 'AvenirNextLTPro-Bold',
  },
  cardNumberView: {
    flexDirection: 'row',
    height: height * 0.03,
    width: '100%',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    marginTop: height * 0.02,
  },
  cardNumberViewSec: {
    flexDirection: 'row',
    height: height * 0.025,
    width: '100%',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    marginTop: height * 0.005,
  },
  flexstart: {
    alignSelf: 'flex-start',
    marginTop: -height * 0.006,
  },
  dollarText: {
    fontSize: normalize(13),
    fontWeight: 'bold',
    color: 'white',
    fontFamily: 'AvenirNextLTPro-Bold',
  },
  limitTextDesc: {
    fontSize: normalize(14),
    color: '#22222266',
    fontFamily: 'AvenirNextLTPro-Regular',
    marginTop: height * 0.03,
  },
  buttonsView: {
    height: height * 0.05,
    width: width * 0.9,
    marginTop: height * 0.04,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  button: {
    width: width * 0.28,
    height: '100%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EFFBF5',
    borderRadius: width * 0.01,
  },
  buttontext: {
    color: '#01D167',
    fontSize: normalize(15),
    fontFamily: 'AvenirNextLTPro-Demi',
  },
  abText: {
    fontSize: normalize(14),
    color: 'white',
    marginTop: height * 0.03,
    fontFamily: 'AvenirNextLTPro-Regular',
  },
  hsText: {
    fontSize: normalize(12),
    fontWeight: '500',
    color: '#06D166',
    fontFamily: 'AvenirNextLTPro-Demi',
  },
  abView: {
    width: width * 0.3,
    height: height * 0.04,
    marginTop: height * 0.02,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  abIconView: {
    height: height * 0.035,
    alignSelf: 'flex-start',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#06D166',
    borderRadius: width * 0.015,
    width: width * 0.12,
    marginTop: height * 0.01,
  },
  cardView: {
    height: height * 0.28,
    width: width * 0.9,
    alignSelf: 'center',
    backgroundColor: '#06D166',
    borderRadius: width * 0.04,
    marginTop: -height * 0.085,
    alignItems: 'center',
    justifyContent: 'center',
    padding: width * 0.05,
  },
  hideCardNumberView: {
    width: width * 0.35,
    backgroundColor: 'white',
    borderRadius: width * 0.02,
    height: height * 0.06,
    alignSelf: 'flex-end',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    paddingLeft: width * 0.03,
    paddingRight: width * 0.03,
    paddingBottom: height * 0.018,
  },
  hs_icon: {
    width: width * 0.04,
    height: width * 0.04,
    resizeMode: 'contain',
  },
  aspireLogo: {
    height: height * 0.05,
    width: width * 0.2,
    resizeMode: 'contain',
    alignSelf: 'flex-end',
  },
  cardText: {
    color: 'white',
    fontSize: normalize(15),
    letterSpacing: width * 0.01,
    marginRight: width * 0.05,
    fontFamily: 'AvenirNextLTPro-Regular',
  },
  cardTextSec: {
    color: 'white',
    fontSize: normalize(15),
    letterSpacing: width * 0.005,
    marginRight: width * 0.05,
    fontFamily: 'AvenirNextLTPro-Regular',
  },
  tabbar: {
    height: height * 0.08,
    flexDirection: 'row',
    marginTop: height * 0.02,
  },
  tabLogo: {
    height: height * 0.04,
    width: height * 0.04,
    resizeMode: 'contain',
  },
  textView: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    marginLeft: width * 0.03,
    width: width * 0.7,
  },
  tabHText: {
    fontSize: normalize(16),
    color: '#25345F',
    fontFamily: 'AvenirNextLTPro-Demi',
  },
  tabDText: {
    fontSize: normalize(13),
    color: '#A7A7A7',
    fontFamily: 'AvenirNextLTPro-Regular',
  },
  saveButton: {
    height: height * 0.07,
    width: width * 0.7,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: width * 0.1,
    backgroundColor: '#EEEEEE',
    marginTop: height * 0.3,
  },
  saveButtonText: {
    color: '#ffffff',
    fontFamily: 'AvenirNextLTPro-Demi',
    fontSize: normalize(16),
  },
  shadowProp: {
    shadowColor: '#0000001F',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
});

export default styles;
